name: Deploy Frontend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t dimland/image-generator-frontend:latest ./
          docker push dimland/image-generator-frontend:latest

      - name: Deploy frontend to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
            docker pull dimland/image-generator-frontend:latest
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker run -d --name frontend-container --restart always --network my-net -p 3000:80 dimland/image-generator-frontend:latest
